version: '3'
services:
  nuxt-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
